title                       : ODT Research
author                      : ODT Researchers
copyright                   : "2024"
logo                        : logo.png

execute:
  execute_notebooks: force         # force, auto, cache, 'off'  https://jupyterbook.org/content/execute.html

repository:
  url: https://github.com/byu-books/odtresearch
  branch: master                   # default branch

html:                              # github buttons
  use_issues_button:       true
  use_repository_button:   true
  use_edit_page_button:    true
  extra_navbar: ""

only_build_toc_files: true

parse:
  myst_enable_extensions:
    #- amsmath
    #- attrs_inline
    #- colon_fence
    #- deflist
    #- dollarmath
    #- fieldlist
    #- html_admonition
    - html_image
    #- linkify
    #- replacements
    #- smartquotes
    #- strikethrough
    #- substitution
    #- tasklist

launch_buttons:
    thebe: false
